### ISSUE TITLE
Replication of data included in chart

### ISSUE THREAD

**Issue by snissn** [application-research/storage-market-api#3]
For data storage solutions, data replication is an important property that can be under the hood and not necesssarily front and center.

S3 offers a solution for storing your data in just 1 availability zone to save costs, while they also offer 3 availability zones by default:

![image](https://user-images.githubusercontent.com/1981537/209237024-7605d8ec-8158-4313-aa05-fce7a18153a2.png)

this would be a 3x difference in pricing on filecoin.

Also this replication is for within a geographic region but 3 different "availability zones" which correspond to data centers within a few miles of each other. 

Because we have a distributed file storage network, we generallly will do replication across vast geographical regions by default! There's ways to do geographic replication with s3, but they will also increase the cost and isn't the default https://docs.aws.amazon.com/AmazonS3/latest/userguide/replication.html

**Comment by jimmylee** [comment]
We included a replication column here https://github.com/application-research/storage-market-api/blob/main/scripts/create-market-table.js
